src/Entity/Transaction.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use App\Repository\TransactionRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=TransactionRepository::class)
 */
class Transaction
{
     /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\ManyToOne(targetEntity=Bien::class, inversedBy="transactions",cascade={"remove"})
     */
    private $bien;

    /**
     * @ORM\ManyToOne(targetEntity=Operation::class, inversedBy="transactions",cascade={"remove"})
     */
    private $operation;

    /**
     * @ORM\Column(type="float")
     */
    private $qte;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     * @Assert\NotEqualTo(propertyPath="magasin_distination")
     */
    private $magasin_source;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     * @Assert\NotEqualTo(propertyPath="magasin_source")
     */
    private $magasin_distination;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_unitaire;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_totale;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getBien(): ?Bien
    {
        return $this->bien;
    }

    public function setBien(?Bien $bien): self
    {
        $this->bien = $bien;

        return $this;
    }

    public function getOperation(): ?Operation
    {
        return $this->operation;
    }

    public function setOperation(?Operation $operation): self
    {
        $this->operation = $operation;

        return $this;
    }

    public function getQte(): ?float
    {
        return $this->qte;
    }

    public function setQte(float $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getMagasinSource(): ?string
    {
        return $this->magasin_source;
    }

    public function setMagasinSource(string $magasin_source): self
    {
        $this->magasin_source = $magasin_source;

        return $this;
    }

    public function getMagasinDistination(): ?string
    {
        return $this->magasin_distination;
    }

    public function setMagasinDistination(string $magasin_distination): self
    {
        $this->magasin_distination = $magasin_distination;

        return $this;
    }

    public function getPrixUnitaire(): ?float
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(float $prix_unitaire): self
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    public function getPrixTotale(): ?float
    {
        return $this->prix_totale;
    }

    public function setPrixTotale(float $prix_totale): self
    {
        $this->prix_totale = $prix_totale;

        return $this;
    }
    public function calcul(): ?float
    {
        $pt=$this->getPrixUnitaire()*$this->getQte();
        return $pt;
        
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

  

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

}

src/Form/TransactionType.php
<?php

namespace App\Form;

use App\Entity\Magasin;
use App\Entity\Operation;
use App\Entity\Transaction;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;


class TransactionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('qte')
            ->add('magasin_distination',EntityType::class, [
                
                'class' => Magasin::class,
                'required' => false,
                'choice_label' => 'annotation',
                'placeholder' => ' choisissez magasin distination'
            ])
            ->add('magasin_source',EntityType::class, [
                
                'class' => Magasin::class,
                'required' => false,
                'choice_label' => 'annotation',
                'placeholder' => ' choisissez magasin source'
            ]

            )
            
            ->add('prix_unitaire')
            
            ->add('bien')
            ->add('operation',EntityType::class, [
                
                'class' => Operation::class,
                'placeholder' => 'choisissez l operation'
            ])
            
        ;
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Transaction::class,
        ]);
    }
}

src/Controller/TransactionController.php
<?php

namespace App\Controller;

use App\Entity\Transaction;
use App\Form\TransactionType;
use App\Repository\TransactionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/transaction")
 */
class TransactionController extends AbstractController
{
    /**
     * @Route("/", name="transaction_index", methods={"GET"})
     */
    public function index(TransactionRepository $transactionRepository): Response
    {
        return $this->render('transaction/index.html.twig', [
            'transactions' => $transactionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="transaction_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $transaction = new Transaction();
        $form = $this->createForm(TransactionType::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $transaction->setPrixTotale($transaction->calcul());
           # dd($transaction);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($transaction);
            $entityManager->flush();

            return $this->redirectToRoute('transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('transaction/new.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_show", methods={"GET"})
     */
    public function show(Transaction $transaction): Response
    {
        return $this->render('transaction/show.html.twig', [
            'transaction' => $transaction,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="transaction_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Transaction $transaction): Response
    {
        $form = $this->createForm(TransactionType::class, $transaction);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('transaction_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('transaction/edit.html.twig', [
            'transaction' => $transaction,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="transaction_delete", methods={"POST"})
     */
    public function delete(Request $request, Transaction $transaction): Response
    {
        if ($this->isCsrfTokenValid('delete'.$transaction->getBien(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($transaction);
            $entityManager->flush();
        }

        return $this->redirectToRoute('transaction_index', [], Response::HTTP_SEE_OTHER);
    }
  
}

templates/transaction/_delete_form.html.twig
<form method="post" action="{{ path('transaction_delete', {'id': transaction.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ transaction.bien) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/transaction/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.bien) }}
    {{ form_row(form.operation) }}
    {{ form_row(form.qte) }}
    
    {{ form_row(form.prix_unitaire) }}

    <div style="display: none;" class="block_magasin_source">
    {{ form_row(form.magasin_source) }}
    </div>
    <div style="display: none;" class="block_magasin_distination">
    {{ form_row(form.magasin_distination) }}
    </div>
    
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}
{% block javascripts %}
    
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            
    <script>
    jQuery( document ).ready(function() {
    jQuery('#transaction_operation').on('change', function() {
    if( $(this).find("option:selected").text() == 'entree' ){
        
        jQuery('.block_magasin_distination').show();
        jQuery('.block_magasin_source').hide();
    }
    else if( $(this).find("option:selected").text() == 'sortie'){
        
        jQuery('.block_magasin_distination').hide();
        jQuery('.block_magasin_source').show();
    }
    else {
        jQuery('.block_magasin_distination').show();
        jQuery('.block_magasin_source').show();
    }
    ;})

    console.log( "ready!" );
});
 
</script>
{% endblock %}

templates/transaction/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Transaction{% endblock %}

{% block body %}
<div id="layoutSidenav_content">
    <h1>Modification de Transaction</h1>
   <div> 
    {{ include('transaction/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('transaction_index') }}"class="btn btn-secondary">retour à la liste des transactions</a>

    {{ include('transaction/_delete_form.html.twig') }}
    </div>
</div>
{% endblock %}

templates/transaction/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Transaction index{% endblock %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="{{asset('css/styles.css')}}" rel="stylesheet" />
    
    
{% endblock %}
{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{{asset('js/scripts.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="{{asset('js/datatables-simple-demo.js')}}"></script>
    
{% endblock %}  

{% block body %}

<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Tableau des transactions
                </div>
                
                <div class="card-body">
    <table  id="datatablesSimple">
        <thead>
            <tr>
                <th>Bien</th>
                <th>Operation</th>
                <th>Qte</th>
                <th>Magasin_source</th>
                <th>Magasin_distination</th>
                <th>Prix_unitaire</th>
                <th>Prix_totale</th>
                <th>date de creation</th>
                <th>date de modification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.bien }}</td>
                <td>{{ transaction.operation }}</td>
                <td>{{ transaction.qte }}</td>
                <td>{{ transaction.magasinSource }}</td>
                <td>{{ transaction.magasinDistination }}</td>
                <td>{{ transaction.prixUnitaire }}</td>
                <td>{{ transaction.PrixTotale }}</td>
                <td>{{ transaction.createdAt|date('d/m/Y H:i:s')  }}</td>
                <td>{{ transaction.updatedAt|date('d/m/Y H:i:s') }}</td>
                <td>
                    <a href="{{ path('transaction_show', {'id': transaction.id}) }}"  class="btn btn-info">info</a>
                    <a href="{{ path('transaction_edit', {'id': transaction.id}) }}" class="btn btn-success">modification</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr><a href="{{ path('transaction_new') }}" class="btn btn-primary">nouvelle transaction</a></tr>
        
        </tfoot>
    </table>
                </div>
            </div>
            
       </div>
    </main>     
    
    
    
</div>
{% endblock %}

templates/transaction/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Transaction{% endblock %}

{% block body %}
<div id="layoutSidenav_content">
<div>
    <h1>nouvelle transaction</h1>

    {{ include('transaction/_form.html.twig') }}

    <a href="{{ path('transaction_index') }}" class="btn btn-secondary">retour à la liste</a>
</div>
</div>    
{% endblock %}

templates/transaction/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transaction{% endblock %}

{% block body %}
<div id="layoutSidenav_content">
    <table class="table">
        <tbody>
            <tr>
                <th>Qte</th>
                <td>{{ transaction.qte }}</td>
                <td></td>
            </tr>
            <tr>
                <th>Magasin_source</th>
                <td>{{ transaction.magasinSource }}</td>
                <td></td>
            </tr>
            <tr>
                <th>Magasin_distination</th>
                <td>{{ transaction.magasinDistination }}</td>
                <td></td>
            </tr>
            <tr>
                <th>Prix_unitaire</th>
                <td>{{ transaction.prixUnitaire }}</td>
                <td></td>
            </tr>
            <tr>
                <th>Prix_totale</th>
                <td>{{ transaction.prixTotale }}</td>
                <td></td>
            </tr>
            <tr>
                <td><a href="{{ path('transaction_index') }}"class="btn btn-secondary">retour à la liste des utilisteurs</a></td>
                <td><a href="{{ path('transaction_edit', {'id': transaction.id}) }}"class="btn btn-success">modification</a></td>
                <td>{{ include('transaction/_delete_form.html.twig') }}</td>
            </tr>
        </tbody>
    </table>

    

    

    
</div>
{% endblock %}